export const data=[
    {
        id:1,
        name:'Boil Egg',
        catagory:'breakfast',
        price:'$3',
        ImageUrl:'assests/b3.jpg'
    },
    {
        id:2,
        name:'Pizza',
        catagory:'Lunch',
        price:'$10',
        ImageUrl:'assests/lunch1.jpeg'
    },
    {
        id:3,
        name:'Burger',
        catagory:'Lunch',
        price:'$5',
        ImageUrl:'assests/lunch2.jpg'
    },
    {
        id:4,
        name:'Chai',
        catagory:'BreakFast',
        price:'$5',
        ImageUrl:'assests/b1.jpg'
    },
    {
        id:5,
        name:'Handi',
        catagory:'Dinner',
        price:'$8',
        ImageUrl:'assests/dinner2.jpg'
    },
    {
        id:6,
        name:'Family_Fest',
        catagory:'Dinner',
        price:'$13',
        ImageUrl:'assests/dinner1.jpeg'
    },
    {
        id:7,
        name:'Cake_Tea',
        catagory:'breakfast',
        price:'$6',
        ImageUrl:'assests/b2.jpg'
    },
    {
        id:8,
        name:'Chines',
        catagory:'Lunch',
        price:'$3',
        ImageUrl:'assests/lunch4.jpg'
    },
    {
        id:9,
        name:'Turkish_dinn',
        catagory:'Dinner',
        price:'$29',
        ImageUrl:'assests/dinner3.jpeg'
    },
    {
        id:10,
        name:'Chesee-Bug',
        catagory:'Lunch',
        price:'$9',
        ImageUrl:'assests/lunch2.jpg'
    },
  
]